/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface EditFle {
    'home': RouterHistory;
    'match': MatchResults;
  }
  interface EditFleAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FirstComponent {}
  interface FirstComponentAttributes extends StencilHTMLAttributes {}

  interface MyDetail {
    'match': MatchResults;
  }
  interface MyDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface NewPage {
    'home': RouterHistory;
  }
  interface NewPageAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface SuprimerFle {
    'match': MatchResults;
  }
  interface SuprimerFleAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'EditFle': Components.EditFle;
    'FirstComponent': Components.FirstComponent;
    'MyDetail': Components.MyDetail;
    'NewPage': Components.NewPage;
    'SuprimerFle': Components.SuprimerFle;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'edit-fle': Components.EditFleAttributes;
    'first-component': Components.FirstComponentAttributes;
    'my-detail': Components.MyDetailAttributes;
    'new-page': Components.NewPageAttributes;
    'suprimer-fle': Components.SuprimerFleAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLEditFleElement extends Components.EditFle, HTMLStencilElement {}
  var HTMLEditFleElement: {
    prototype: HTMLEditFleElement;
    new (): HTMLEditFleElement;
  };

  interface HTMLFirstComponentElement extends Components.FirstComponent, HTMLStencilElement {}
  var HTMLFirstComponentElement: {
    prototype: HTMLFirstComponentElement;
    new (): HTMLFirstComponentElement;
  };

  interface HTMLMyDetailElement extends Components.MyDetail, HTMLStencilElement {}
  var HTMLMyDetailElement: {
    prototype: HTMLMyDetailElement;
    new (): HTMLMyDetailElement;
  };

  interface HTMLNewPageElement extends Components.NewPage, HTMLStencilElement {}
  var HTMLNewPageElement: {
    prototype: HTMLNewPageElement;
    new (): HTMLNewPageElement;
  };

  interface HTMLSuprimerFleElement extends Components.SuprimerFle, HTMLStencilElement {}
  var HTMLSuprimerFleElement: {
    prototype: HTMLSuprimerFleElement;
    new (): HTMLSuprimerFleElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'edit-fle': HTMLEditFleElement
    'first-component': HTMLFirstComponentElement
    'my-detail': HTMLMyDetailElement
    'new-page': HTMLNewPageElement
    'suprimer-fle': HTMLSuprimerFleElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'edit-fle': HTMLEditFleElement;
    'first-component': HTMLFirstComponentElement;
    'my-detail': HTMLMyDetailElement;
    'new-page': HTMLNewPageElement;
    'suprimer-fle': HTMLSuprimerFleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
